server:
  port: 7082
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/

management:
  endpoints:
    web:
      exposure: 
        include: *
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG