server:
  port: 7082
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:7070/eureka/
